# +---------------------------------------------------------------+
# |                                                               |
# |   Project: Spicord                                            |
# |   Author: OopsieWoopsie                                       |
# |   License: AGPL-3.0                                           |
# |   GitHub: https://github.com/OopsieWoopsie/Spicord            |
# |                                                               |
# +---------------------------------------------------------------+

##> Your list of bots here.
bots:
  default:
    command-support: true
    command-prefix: "-"
    token: "YOUR BOT TOKEN HERE"
    enabled: false
    addons:
    - "spicord::info"
    - "spicord::plugins"
    - "spicord::players"
#  another-bot:
#    command-support: false
#    command-prefix: "!"
#    token: "YOUR BOT TOKEN HERE"
#    enabled: false
#    addons: []

##> Change the value to "false" if you want to disable the debug messages.
enable-debug-messages: false

##> Change the value to "true" if you want to enable the JDA messages.
enable-jda-messages: true

##> Do not change this.
config-version: 1